### ISSUE TITLE
Easy Model Modification

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/ml-rainbow#1]
## Description

Currently many values are hard coded in some lines, it would be beneficial to have them as globals to be easily adaptable.

## Must Include

- [ ] Place to modify constants
- [ ] Comments on what they are if new person looks  at it

## Notes

Good example for this is the frame size of currently 180. I don't want to search for it to change it.

**Comment by valentindoering** [comment]
done
