### ISSUE TITLE
Realtime LSTM Seq

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/ml-rainbow#16]
## Description

This is the parent issue to write a realtime LSTM Model that can predict during recording in multiple values per recording.

## Must Include

- [x] #20
- [ ] A finished model according to above

## Notes

please note all child issues working towards this in Must Includes with Issue Number and Title

**Comment by lucasliebe** [comment]
First architecture is discuss by valentin, franz and leander. Please write child issues for parts to work on, in order to document development and split load!

**Comment by FranzSw** [comment]
dropped because of new issues / model
