### ISSUE TITLE
Explore LSTM

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/ml-rainbow#2]
## Description

Test out to add a layer of LSTM over a time series and experiment.

## Must Include

- [x] good understanding of writing an LSTM
- [x] see how a model like this is included in Kotlin

## Notes

requires more How To then real implementation for now

**Comment by leandermasopust** [comment]
Paper referencing MLSTM-FCNs/MALSTM_FCNs: [https://arxiv.org/pdf/1801.04503v2.pdf](url)
Implementation for Human Activity Recognition (HAR) : [https://github.com/houshd/MLSTM-FCN/blob/master/har_model.py](url)
