### ISSUE TITLE
Exploring GRU (RNN)

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/ml-rainbow#23]
## Description

GRUs are a more performant way of LSTMs but most of the time not quite as accurate. Still for our mobile application these might be interesting.

## Must Include

- [ ] an Implementation of the a working LSTM Model as GRU Model
- [ ] comparisons in accuracy and if there is noticeable performance improvement

**Comment by leandermasopust** [comment]
not needed/prioritized in current project state
