### ISSUE TITLE
convert delta velocity to acceleration

### ISSUE THREAD

**Issue by leandermasopust** [Sensors-in-Paradise/ml-rainbow#25]
## Description

Write a Script to convert the delta velocity columns of all sensors to acceleration and save new csvs in an extra folder

## Must Include

- [x] convert delta velocity columns to acceleration
- [x] save modified dataframes into new csv files

**Comment by kpostnov** [comment]
The SDK converts dv to acceleration by using this formula:
`dv / dt`
where `dt` is something in between

- 0.01667102150011737

- 0.016666127130012

- 0.01666642277398037

**Comment by lucasliebe** [comment]
dv[1] = x 
dv[2] = y
dv[3] = z
