### ISSUE TITLE
filter recordings with alot of NaN values

### ISSUE THREAD

**Issue by leandermasopust** [Sensors-in-Paradise/ml-rainbow#27]
## Description

filter recordings for a variable maximum of missing values 
(optional: parametrize for sum of missing sensor values, maximum of missing sensor values, mean of missing sensor values, percentagewise / total missing time)

**Comment by lucasliebe** [comment]
first of all I will work on implementing a method used to save recordings without retransmissions than we can evaluate nan values again afterwards

**Comment by lucasliebe** [comment]
not necessary after retransmission removal and the merge of completely different timeframes
