### ISSUE TITLE
adjust current implementations to new Recording/Window structure

### ISSUE THREAD

**Issue by leandermasopust** [Sensors-in-Paradise/ml-rainbow#28]
## Description

with the new load_dataset, we have different columns than before and activity is now a pd.Series instead of a single value.
this leads to errors while trying to build/train/test/evaluate models. refactoring/adjustment to the new structure for those files is needed

## Must Include

- [ ] adjust all model classes to new recording and window structure
- [ ] adjust k-fold-cross-validation to new recording and window structure
- [ ] check for other files that might need adjustment to our new structure

**Comment by lucasliebe** [comment]
will probably be done in ml unicorn
