### ISSUE TITLE
Remove Cloud Credentials from Version Control!

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/ml-rainbow#33]
## Description

Currently we have open credentials in download_recordings.py, these should definitely be partially removed.

## Must Include

- [ ] At least remove the password from version control!

**Comment by kpostnov** [comment]
Once the credentials entered VC they should be considered compromised. I suggest removing them _and_ changing cloud credentials immediatly.

**Comment by lucasliebe** [comment]
is worked on in branch 27-retransmissions-removal

**Comment by lucasliebe** [comment]
is basically done, data quality just is not moved into master
